-- auto Generated on 2017-12-30 16:52:48 
-- DROP TABLE IF EXISTS `user1`; 
CREATE TABLE user1(
    `id` INTEGER(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'createTime',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updateTime',
    `password` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'password',
    `username` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'username',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'user1';
